version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: registry_db
    environment:
      POSTGRES_USER: sber
      POSTGRES_PASSWORD: password
      POSTGRES_DB: registry
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
